# Generated by Django 3.2.3 on 2021-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50, verbose_name='Наименование акции')),
                ('stock_sector', models.CharField(max_length=200, verbose_name='Сектор')),
                ('stock_industry', models.CharField(max_length=200, verbose_name='Индустрия')),
                ('stock_activity', models.BooleanField(verbose_name='Активность акции')),
                ('stock_identifier', models.CharField(max_length=50, verbose_name='Идентификатор')),
            ],
        ),
    ]
