# Generated by Django 3.2.3 on 2021-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор'),
        ),
    ]
