# Generated by Django 3.2.3 on 2021-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_stock_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка'),
        ),
    ]
