# Generated by Django 3.2.3 on 2021-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_stock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тикер'),
        ),
    ]
