# Generated by Django 3.2.3 on 2021-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_stock_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_identifier',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_url',
        ),
        migrations.AddField(
            model_name='stock',
            name='investing_dentifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор investing.com'),
        ),
        migrations.AddField(
            model_name='stock',
            name='tradingview_dentifier',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Идентификатор tradingview.com'),
        ),
    ]
