# Generated by Django 3.2.3 on 2021-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210609_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='investing_dentifier',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Идентификатор investing.com'),
        ),
    ]
