# Generated by Django 3.2.3 on 2021-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_investing_dentifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=50, verbose_name='Тикер')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('source', models.CharField(max_length=200, verbose_name='Источник данных')),
                ('json_value', models.JSONField()),
            ],
        ),
    ]
