# Generated by Django 3.2.3 on 2021-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_sourcedatacompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedatacompany',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
