# Generated by Django 3.2.3 on 2021-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_sourcedatacompany_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedatacompany',
            options={'verbose_name': 'Исходные данные по компании', 'verbose_name_plural': 'Исходные данные по компании'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='sourcedatacompany',
            name='json_value',
            field=models.JSONField(default={}),
        ),
    ]
