# Generated by Django 3.2.3 on 2021-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210618_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedatacompany',
            name='json_value',
            field=models.JSONField(),
        ),
    ]
