version: '3.7'

services:
  backend:
    container_name: backend
    image: $CI_REGISTRY/$CI_PROJECT_PATH/backend:${CI_COMMIT_SHA}
    # build:
    #   context: ./backend
    env_file:
      - .env
    volumes:
      - /var/www/static:/static
#      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: $CI_REGISTRY/$CI_PROJECT_PATH/db:${CI_COMMIT_SHA}
    container_name: db
    # build:
    #   context: ./db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    image: $CI_REGISTRY/$CI_PROJECT_PATH/frontend:${CI_COMMIT_SHA}
    container_name: frontend
    # build: ./frontend
    volumes: 
      - ./frontend/src:/app/src
    ports:
      - '8080:8080'
    restart: unless-stopped
    command: npm run serve
    depends_on:
      - backend

volumes:
  pgdata:
  static:

networks:
  default:
    name: stock
