server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      app: docker
      __path__: /var/log/containers/*/*-json.log
  pipeline_stages:
    - match:
        selector: '{app="docker"}'
        stages:
          - json:
              expressions:
                output:    log
                stream:    stream
                timestamp: time
                attrs:
          - json:
              expressions:
                name:
              source: attrs
          - labels:
              name: