version: "3.7"

services:
  test:
    image: $CI_REGISTRY/$CI_PROJECT_PATH/web:${CI_COMMIT_SHA}
    env_file:
      - .env
    command: bash -c "pip install pytest-html && pytest -vvl --html=/test-report/pytest-report.html --self-contained-html"
    volumes:
      - ./test-report:/test-report
    restart: "no"
    depends_on:
      - db
      - redis

  test-quality:
    image: $CI_REGISTRY/$CI_PROJECT_PATH/web:${CI_COMMIT_SHA}
    env_file:
      - .env
    command: bash -c "pip install flake8-html && flake8 --format=html --htmldir=/flake-report --show-source ./"
    volumes:
      - ./flake-report:/flake-report
    restart: "no"
    depends_on:
      - db
      - redis



